@startuml
!include https://raw.githubusercontent.com/Kyrales/1C-ER-plantuml/refs/heads/extended/main.puml

header 123 
title ER-диаграмма взаимосвязи объектов подсистемы учета подарочных сертификатов
caption Пример диаграммы объектов
footer Проектная работа в УЦ ОТУС

package НСИ <<folder>> {

    _Справочник(ВидПодарочныхСертификатов, "Виды подарочных сертификатов")
    _Справочник(ПодарочныйСертификат, "Подарочные сертификаты")

}

package УчетныеМеханизмы <<folder>> {

    _Перечисление(СтатусыПодарочныхСертификатов, "Статусы подарочных сертификатов"){
        Выпущен
        Активирован
        ЧастичноИспользован
        ПолностьюИспользован
        Возвращен
        Аннулирован
    }
    _РегистрСведений(ИсторияСтатусовПодарочныхСертификатов, "История статусов подарочных сертификатов") {
            <$d> ПодарочныйСертификат
            <$r> Статус
            <$r> ДействуетДо
        }

    _РегистрНакопления(СуммыПодарочныхСертификатов, "Подарочные сертификаты") {
        <$d> ПодарочныйСертификат
        <$r> Сумма    
    }

}

package Операции <<folder>> {

    _Документ(ВводОстатковПодарочныхСертификатов, "Ввод остатков подарочных сертификатов") {
        ВидПодарочныхСертификатов
        Ответственный
        Комментарий
        ОстатокСуммы
        -- ПодарочныеСертификаты --
        ПодарочныйСертификат
        Статус
        ОстатокСуммы
        ДействуетДо
    }
    _Документ(ВыпускПодарочныхСертификатов, "Выпуск подарочных сертификатов") {
        ВидПодарочныхСертификатов
        Ответственный
        Комментарий
        Сумма
        -- ПодарочныеСертификаты --
        ПодарочныйСертификат
    }

    _Документ(РеализацияПодарочныхСертификатов, "Реализация подарочных сертификатов") {
        Ответственный
        Комментарий
        -- ПодарочныеСертификаты --
        ПодарочныйСертификат
    }   

    _Документ(_ДемоРеализацияТоваров, "Демо: Реализация товаров") {
        Реквизиты
        -- ОплатаПодарочнымиСертификатами --
        ПодарочныйСертификат
        СуммаОплаты
    }

    _Документ(ВозвратПодарочныхСертификатов, "Возврат подарочных сертификатов") {
        Ответственный
        Комментарий
        -- ПодарочныеСертификаты --
        ПодарочныйСертификат
    }
    
    _Документ(АннулированиеПодарочныхСертификатов, "Аннулирование подарочных сертификатов") {
        ВидПодарочныхСертификатов
        Ответственный
        Комментарий
        -- ПодарочныеСертификаты --
        ПодарочныйСертификат
    }     
}

ВидПодарочныхСертификатов --> ПодарочныйСертификат::Владелец
ВидПодарочныхСертификатов --> ВводОстатковПодарочныхСертификатов::ВидПодарочныхСертификатов
ВидПодарочныхСертификатов --> ВыпускПодарочныхСертификатов::ВидПодарочныхСертификатов
ВидПодарочныхСертификатов --> АннулированиеПодарочныхСертификатов::ВидПодарочныхСертификатов

ПодарочныйСертификат --> ВводОстатковПодарочныхСертификатов::ПодарочныйСертификат
ПодарочныйСертификат --> ВыпускПодарочныхСертификатов::ПодарочныйСертификат
ПодарочныйСертификат --> РеализацияПодарочныхСертификатов::ПодарочныйСертификат
ПодарочныйСертификат --> _ДемоРеализацияТоваров::ПодарочныйСертификат
ПодарочныйСертификат --> ВозвратПодарочныхСертификатов::ПодарочныйСертификат
ПодарочныйСертификат --> АннулированиеПодарочныхСертификатов::ПодарочныйСертификат

СтатусыПодарочныхСертификатов --> ВводОстатковПодарочныхСертификатов::Статус
СтатусыПодарочныхСертификатов --> ИсторияСтатусовПодарочныхСертификатов::Статус

ВводОстатковПодарочныхСертификатов --> ИсторияСтатусовПодарочныхСертификатов
ВводОстатковПодарочныхСертификатов --> СуммыПодарочныхСертификатов

ВыпускПодарочныхСертификатов --> ИсторияСтатусовПодарочныхСертификатов

РеализацияПодарочныхСертификатов --> ИсторияСтатусовПодарочныхСертификатов
РеализацияПодарочныхСертификатов --> СуммыПодарочныхСертификатов

_ДемоРеализацияТоваров --> ИсторияСтатусовПодарочныхСертификатов
_ДемоРеализацияТоваров --> СуммыПодарочныхСертификатов

ВозвратПодарочныхСертификатов --> ИсторияСтатусовПодарочныхСертификатов
ВозвратПодарочныхСертификатов --> СуммыПодарочныхСертификатов

АннулированиеПодарочныхСертификатов --> ИсторияСтатусовПодарочныхСертификатов
АннулированиеПодарочныхСертификатов --> СуммыПодарочныхСертификатов
@enduml